import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}>
        <nav className="w-full bg-gray-100 border-b border-gray-300 shadow-sm mb-8">
          <div className="max-w-4xl mx-auto flex items-center justify-center h-16">
            <a href="/" className="px-4 py-2 text-lg font-semibold text-gray-700 hover:text-blue-600">Welcome</a>
            <a href="/projects" className="px-4 py-2 text-lg font-semibold text-gray-700 hover:text-blue-600">Projects</a>
            <a href="/resume" className="px-4 py-2 text-lg font-semibold text-gray-700 hover:text-blue-600">Resume</a>
            <a href="/contact" className="px-4 py-2 text-lg font-semibold text-gray-700 hover:text-blue-600">Contact</a>
          </div>
        </nav>
        <div className="max-w-4xl mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
